{
 "title": "Mirrormaker2 Lag Exporter Dashboard",
 "description": "This grafana dashboard provides the lag information of mirrormaker 2 process",
 "tags": [
  "strimzi",
  "mirrormaker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sourcecluster",
    "label": "Source_Cluster",
    "query": {
     "query": "query_result(mirrormaker_source_topics_logendoffset)"
    }
   },
   {
    "name": "targetcluster",
    "label": "Target_Cluster",
    "query": {
     "query": "query_result(mirrormaker_source_topics_logendoffset{sourcecluster=~\"$sourcecluster\"})"
    }
   },
   {
    "name": "connector",
    "label": "Mirrormaker_Name",
    "query": {
     "query": "query_result(mirrormaker_source_topics_logendoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\"})"
    }
   },
   {
    "name": "topic",
    "label": "Topic_Name",
    "query": {
     "query": "query_result(mirrormaker_source_topics_logendoffset{connector=~\"$connector\",sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Mirrormaker Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mirrormaker_source_topics_logendoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"}) - sum(mirrormaker_currentoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Total Mirrormaker Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mirrormaker_source_topics_logendoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"}) - sum(mirrormaker_currentoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"})",
     "legendFormat": "mirrormaker connector lag"
    }
   ]
  },
  {
   "title": "Topic wise lag ",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(mirrormaker_source_topics_logendoffset{connector=~\"$connector\",topic=~\".*\"} - mirrormaker_currentoffset{connector=~\"$connector\",topic=~\".*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Level Lag",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mirrormaker_source_topics_logendoffset{connector=~\"$connector\",sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",topic=~\"$topic\",partition=~\".*\"} - mirrormaker_currentoffset{connector=~\"$connector\",sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",topic=~\"$topic\",partition=~\".*\"}",
     "legendFormat": "{{topic}}_{{partition}}"
    }
   ]
  },
  {
   "title": "Topic/Partition level Lag",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(mirrormaker_source_topics_logendoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"} - mirrormaker_currentoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"}) by (topic,partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic - LogEndOffset",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mirrormaker_source_topics_logendoffset{connector=~\"$connector\",sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",topic=~\"$topic\",partition=~\".*\"}",
     "legendFormat": "{{topic}}_{{partition}}"
    }
   ]
  },
  {
   "title": "Topic - CurrentOffset",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mirrormaker_currentoffset{connector=~\"$connector\",sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",topic=~\"$topic\",partition=~\".*\"}",
     "legendFormat": "{{topic}}_{{partition}}"
    }
   ]
  },
  {
   "title": "Topic - LogEndOffset",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mirrormaker_source_topics_logendoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"}) by (topic,partition)",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum(mirrormaker_currentoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"}) by (topic,partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic - LogEndOffset",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mirrormaker_source_topics_logendoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"}) by (topic,partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic - CurrentOffset",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(mirrormaker_currentoffset{sourcecluster=~\"$sourcecluster\",targetcluster=~\"$targetcluster\",connector=~\"$connector\",topic=~\"$topic\"}) by (topic,partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}